verbose: True
interval: 4.0
# centerline: /home/haoru/art/ttl-ws/PUTNAM/traj_opt/optm_1_5/PUTNAM_OPTM_1_5.csv
centerline: tum_lvms_corrected.csv
# centerline: /home/haoru/art/ttl-ws/PUTNAM/enu/PUTNAM_A_CENTER_enu.csv
left_boundary: LVMS_MAIN_INNER_BOUND_enu.csv
right_boundary: LVMS_MAIN_OUTTER_BOUND_enu.csv
output: LVMS_A_OPTM_1_0.csv

# centerline: MONZA_UNOPTIMIZED_LINE_enu.csv
# # centerline: /home/haoru/art/ttl-ws/PUTNAM/enu/PUTNAM_A_CENTER_enu.csv
# left_boundary: MONZA_LEFT_BOUNDARY_enu.csv
# right_boundary: MONZA_RIGHT_BOUNDARY_enu.csv
# output: MGKT_A_OPTM_1_0.csv


# x0: /home/haoru/art/ttl-ws/PUTNAM/traj_opt/x_optm.txt
# u0: /home/haoru/art/ttl-ws/PUTNAM/traj_opt/u_optm.txt
# t0: /home/haoru/art/ttl-ws/PUTNAM/traj_opt/t_optm.txt

max_iter: 1000 # max iteration of IPOPT
tol: 0.00001 # convergence tolerance of IPOPT
constr_viol_tol: 0.1 # constraint violation tolerance of IPOPT
speed_cap: 80.0 # overall speed limit (m/s)
average_track_width: 15 # a resonable track width (m) assumption to scale the NLP nicely

estimates: # some initial estimates to warm start the solving
  acc_speed_loopup: # Lookup of acceleration ability at different speed levels. Left is the speed (m/s) and right is the acceleration (m/s^2)
    - [0.0, 10.0]
    - [50.0, 7.0]
    - [100.0, 0.5]
  dcc_speed_lookup:
    - [0.0, -13.0]
    - [50.0, -15.0]
    - [100.0, -20.0]
  max_lon_acc_mpss: 10.0 # max acceleration ability of the vehicle engine
  max_lon_dcc_mpss: -20.0 # max braking ability of the brake
  max_left_acc_mpss: 15.0 # max cornering G (left)
  max_right_acc_mpss: -15.0 # max cornering G (right)
  max_speed_mps: 100.0 # max speed (m/s)
  max_jerk_mpsc: 50.0 # max jerk (m/s^3)

model:
  kd_f: 0.0 # front drive force bias (rear is 1 - kd_f)
  kb_f: 0.55 # front brake force bias (rear is 1 - kb_f)
  mass: 747.52 # mass of car (kg)
  Jzz: 700.0 # MOI around z axis (kg * m^2)
  lf: 1.7203 # cg to front axle (m)
  lr: 1.2514 # cg to rear axle (m)
  twf: 1.6 # front track width (m)
  twr: 1.6 # rear track width (m)
  delta_max: 0.314159 # max front wheel angle (rad)
  vehicle_width: 1.6 # physical vehicle width (m)
  safety_margin_r: 4.5 # safety margin added to vehicle width (m)
  safety_margin_l: 1.5 # safety margin added to vehicle width (m)


  fr: 0.012 # rolling resistance coefficient
  hcog: 0.35 # center of gravity height
  kroll_f: 0.5 # front roll moment distribution

  cl_f: 1.0 # downforce coefficient at front
  cl_r: 1.0 # downforce coefficient at rear
  rho: 1.2041 # air density (kg / m^3)
  A: 1.0 # frontal area (m^2)
  cd: 1.0 # drag coefficient
  mu: 1.3 # tyre - track friction coefficient

  # Bf: 9.62 # magic formula B - front
  # Cf: 2.59 # magic formula C - front
  Bf: 14.15 # magic formula B - front
  Cf: 1.77 # magic formula C - front
  Ef: 1.0 # magic formula E - front
  Fz0_f: 1543.5 # magic formula Fz0 - front
  eps_f: -0.0813 # extended magic formula epsilon - front
  # Br: 8.62 # magic formula B - rear
  # Cr: 2.65 # magic formula C - rear
  Br: 14.15 # magic formula B - front
  Cr: 1.77 # magic formula C - front
  Er: 1.0 # magic formula E - rear
  Fz0_r: 1886.5 # magic formula Fz0 - rear
  eps_r: -0.1263 # extended magic formula epsilon - rear

  Pmax: 339000.0 # motor max power
  Fd_max: 5000.0 # max driver force
  Fb_max: -10000.0 # max brake force
  Td: 0.5 # drive time constant
  Tb: 0.5 # brake time constant
  Tdelta: 0.75 # steering time constant

  