verbose: True
interval: 1.0
centerline: MGKT_CENTER_enu.csv
left_boundary: MGKT_OUT_BOUND_enu.csv
right_boundary: MGKT_IN_BOUND_enu.csv
output: MGKT_OPTM_ENU_TTL_1M.csv

max_iter: 500 # max iteration of IPOPT
tol: 0.1 # convergence tolerance of IPOPT
constr_viol_tol: 0.1 # constraint violation tolerance of IPOPT
speed_cap: 30 # overall speed limit (m/s)
average_track_width: 7 # a resonable track width (m) assumption to scale the NLP nicely

estimates: # some initial estimates to warm start the solving
  acc_speed_loopup: # Lookup of acceleration ability at different speed levels. Left is the speed (m/s) and right is the acceleration (m/s^2)
    - [0.0, 5.0]
    - [15.0, 2.5]
    - [30.0, 0.5]
  dcc_speed_lookup:
    - [0.0, -10.0]
    - [15.0, -10.0]
    - [30.0, -10.0]
  max_lon_acc_mpss: 5.0 # max acceleration ability of the vehicle engine
  max_lon_dcc_mpss: -10.0 # max braking ability of the brake
  max_left_acc_mpss: 10.0 # max cornering G (left)
  max_right_acc_mpss: -10.0 # max cornering G (right)
  max_speed_mps: 25.0 # max speed (m/s)
  max_jerk_mpsc: 10.0 # max jerk (m/s^3)

model:
  kd_f: 0.0 # front drive force bias (rear is 1 - kd_f)
  kb_f: 0.0 # front brake force bias (rear is 1 - kb_f)
  mass: 209.0 # mass of car (kg)
  Jzz: 209.0 # MOI around z axis (kg * m^2)
  lf: 0.55 # cg to front axle (m)
  lr: 0.45 # cg to rear axle (m)
  twf: 1.0 # front track width (m)
  twr: 1.0 # rear track width (m)
  delta_max: 0.314159 # max front wheel angle (rad)
  vehicle_width: 1.0 # physical vehicle width (m)
  safety_margin: 1.0 # safety margin added to vehicle width (m)

  fr: 0.01 # rolling resistance coefficient
  hcog: 0.25 # center of gravity height
  kroll_f: 0.5 # front roll moment distribution

  cl_f: 0.0 # downforce coefficient at front
  cl_r: 0.0 # downforce coefficient at rear
  rho: 1.2041 # air density (kg / m^3)
  A: 0.4 # frontal area (m^2)
  cd: 0.8 # drag coefficient
  mu: 1.5 # tyre - track friction coefficient

  Bf: 9.62 # magic formula B - front
  Cf: 2.59 # magic formula C - front
  Ef: 1.0 # magic formula E - front
  Fz0_f: 512.0 # magic formula Fz0 - front
  eps_f: -0.0813 # extended magic formula epsilon - front
  Br: 8.62 # magic formula B - rear
  Cr: 2.65 # magic formula C - rear
  Er: 1.0 # magic formula E - rear
  Fz0_r: 512.0 # magic formula Fz0 - rear
  eps_r: -0.1263 # extended magic formula epsilon - rear

  Pmax: 6000.0 # motor max power
  Fd_max: 1000.0 # max driver force
  Fb_max: -2000.0 # max brake force
  Td: 1.0 # drive time constant
  Tb: 1.0 # brake time constant
  Tdelta: 1.0 # steering time constant